apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}-env
type: Opaque
data:
  ADMIN_TOKEN: {{ required "adminToken is required" .Values.adminToken | b64enc | quote }}
  {{- with .Values.smtp }}
  SMTP_FROM: {{ .from | b64enc | quote }}
  SMTP_HOST: {{ .host | b64enc | quote }}
  SMTP_PASSWORD: {{ .password | b64enc | quote }}
  SMTP_PORT: {{ .port | b64enc | quote }}
  SMTP_SECURITY: {{ .security | b64enc | quote }}
  SMTP_USERNAME: {{ .username | b64enc | quote }}
  {{- end }}
