apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.http.port }}
      targetPort: http
    - name: ws
      protocol: TCP
      port: {{ .Values.service.ws.port }}
      targetPort: ws
